# Generated by Django 6.0.3 on 2026-03-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.BigIntegerField()),
                ('due_date', models.DateTimeField()),
                ('is_paid', models.CharField(choices=[('Yes', 'yes'), ('No', 'No')], max_length=50)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='Project.project')),
            ],
            options={
                'db_table': 'milestone',
            },
        ),
    ]
