# Generated by Django 6.0.3 on 2026-03-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milestone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(),
        ),
    ]
