# Generated by Django 6.0.3 on 2026-03-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milestone', '0002_alter_milestone_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='is_paid',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
    ]
