# Generated by Django 6.0.3 on 2026-03-21 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Milestone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Pid', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('amount_paid', models.BigIntegerField()),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'CARD'), ('CASH', 'CASH'), ('NET BANKING', 'NET BANKING'), ('CRYPTO', 'CRYPTO')], max_length=100)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Milestone.milestone')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
