# Generated by Django 6.0.3 on 2026-03-24 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_remove_payment_pid_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
