# Generated by Django 6.0.3 on 2026-04-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options_alter_customer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
