# Generated by Django 6.0.3 on 2026-03-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Pid', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=100)),
                ('total_value', models.BigIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Client.client')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
