# Generated by Django 6.0.3 on 2026-03-21 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('platform', models.CharField(choices=[('Fiverr', 'Fiverr'), ('Upwork', 'Upwork'), ('Direct', 'Direct')], max_length=50)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
