# Generated by Django 6.0.3 on 2026-03-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
