# Generated by Django 6.0.3 on 2026-03-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_remove_client_name_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
